-- Submission Instruction:
-- Provide all answers in a new file named solution.sql, ensuring that each question is included as 
-- a comment immediately above its corresponding SQL query.

-- 1. Retrieve all columns from the customer table.
SELECT *
FROM customer;

-- 2. Display only film_id, title, and rating from the film table.
SELECT 
	film_id,
	title,
	rating
FROM film;
	
-- 3. Retrieve the first 15 records from the actor table.
SELECT * 
FROM actor
Limit 15;

-- 4. Retrieve all customers and sort them by last_name in ascending order.
SELECT * 
FROM customer
ORDER BY last_name ASC;

-- 5. Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
SELECT 
	payment_id,
	customer_id,
	amount
FROM payment
ORDER BY amount ASC;

-- 6. Retrieve customers sorted by:
--     - first_name in ascending order
--     - last_name in descending order
SELECT * 
FROM customer
ORDER BY
	first_name ASC,
	last_name DESC;
	
-- 7. Retrieve all payments where the amount is greater than 5.
SELECT *
FROM payment
WHERE amount > 5;
-- 8. Retrieve all payments where the amount is between 3.99 and 6.99.
SELECT *
FROM payment
WHERE amount BETWEEN 3.99 AND 6.99;

-- 9. Retrieve all customers whose first_name starts with the letter J.
SELECT *
FROM customer
WHERE first_name LIKE 'J%';

-- 10. Retrieve all films where the description contains the word “Action”.
SELECT title, description
FROM film
WHERE description LIKE '%Action%';

-- 11. Retrieve payments greater than 7, sorted by amount in descending order.
SELECT *
FROM payment
WHERE amount > 7
ORDER BY amount DESC;

-- 12. Retrieve customers whose first name ends with “n”, sorted alphabetically.
SELECT * 
FROM customer
WHERE first_name LIKE '%n'
ORDER BY first_name;

-- 13. Calculate the total amount spent by each customer.
SELECT 
	customer_id,
	SUM(amount)as total_amount
FROM payment
GROUP BY customer_id;

-- 14. Retrieve the average payment amount per customer.
SELECT 
	customer_id,
	ROUND(AVG(amount), 2) as avg_amount
FROM payment
GROUP BY customer_id

-- 15. Calculate the total revenue generated by each staff member.
SELECT 
	staff_id,
	SUM(amount) as total_revenue
FROM payment
GROUP BY staff_id;

-- 16. Identify the top 5 customers based on total payment amount.
SELECT 
	customer_id,
	SUM(amount) as total_payment
FROM payment
GROUP BY customer_id
ORDER BY total_payment DESC
LIMIT 5;

-- 17. Find the average film length per release year.
SELECT 
	title,
	AVG(length) as avg_length,
	release_year
FROM film
GROUP BY 
	release_year, title;
	
-- 18. Retrieve the highest single payment amount in the payment table.
SELECT *
FROM payment
ORDER BY amount DESC
LIMIT 1;
-- 19. Count how many payments each customer has made.
SELECT 
	customer_id,
	COUNT(payment_id) as total_payment
FROM payment
GROUP BY customer_id
ORDER BY total_payment DESC;

-- 20. Retrieve customers who are active and sort them by first_name.
SELECT *
FROM customer
WHERE active = 1
ORDER BY first_name
