SELECT *
FROM film
where description like '%Drama%'

-- avg length of film by release year


SELECT title, 
	release_year,
	avg(length) avg_length
FROM film
GROUP BY title, release_year
ORDER BY avg_length desc


--total revenue generated by each staff

SELECT staff_id, sum(amount) as total_revenue
FROM payment
GROUP BY staff_id
ORDER BY total_revenue DESC


-- Questions

-- 1. Retrieve all unique customer first names from the customer table.
SELECT DISTINCT first_name 
FROM customer

-- 2. Find the top 5 customers who have spent the most money.

SELECT customer_id, SUM(amount) as amount_spent
FROM payment
GROUP BY customer_id
ORDER BY amount_spent DESC
LIMIT 5


-- Taking this further to include customer first and last name
SELECT p.customer_id, c.first_name, c.last_name, SUM(amount) as amount_spent
FROM payment p
LEFT JOIN customer c ON c.customer_id = p.customer_id
GROUP BY p.customer_id, c.first_name, c.last_name
ORDER BY amount_spent DESC
LIMIT 5


-- 3. List all films with a rental rate greater than 4.00.

SELECT title, rental_rate
FROM film
WHERE rental_rate > 4.00

-- 4. Count the number of payments per customer and display only customers with more than 15 payments.
SELECT customer_id, COUNT(payment_id) as number_of_payments
FROM payment
GROUP BY customer_id
HAVING COUNT(payment_id) > 15
ORDER BY number_of_payments desc
-- 5. Retrieve the first 10 films alphabetically using FETCH.
SELECT title
FROM film
ORDER BY title ASC
FETCH FIRST 10 ROWS ONLY



-- 6. Find the total amount paid per staff member.
SELECT staff_id, SUM(amount) as total_amount
FROM payment
GROUP BY staff_id


-- 7. List customers whose email ends with .org.
SELECT customer_id, CONCAT(first_name, ' ', last_name) as full_name, email
FROM customer
WHERE email LIKE '%.org'


-- 8. Using DISTINCT ON, retrieve the latest payment record per customer.
SELECT DISTINCT ON (customer_id) customer_id, amount, payment_date
FROM payment
ORDER BY customer_id, payment_date DESC

-- 9. Display the average payment amount per customer, ordered from highest to lowest.
SELECT customer_id, AVG(amount) AS avg_payment
FROM payment
GROUP BY customer_id
ORDER BY avg_payment DESC

-- 10. Retrieve all payments made between $2.99 and $5.99.
SELECT *
FROM payment
WHERE amount BETWEEN 2.99 AND 5.99

-- Bonus Challenge

-- - Identify the top 3 cities with the highest number of customers.
SELECT ci.city, SUM(c.customer_id) as no_customer
from customer c
LEFT JOIN address a
ON c.address_id = a.address_id 
LEFT JOIN city ci
ON a.city_id = ci.city_id
GROUP BY ci.city
ORDER BY no_customer DESC
LIMIT 3